configuration:
  - Debug
  - Release

environment:
  CTEST_OUTPUT_ON_FAILURE: 1
  matrix:
  - BUILD: msvc
  - BUILD: msvc
    PLATFORM: x64
  - BUILD: mingw
    QTDIR: C:\Qt\5.9.1\mingw53_32
    PATH : %PATH%;%QTDIR%\bin;C:\MinGW\bin
    build_script:
      - git submodule update --init --recursive
      - qmake .
      - mingw32-make

before_build:
  # Workaround for CMake not wanting sh.exe on PATH for MinGW.
  - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - git submodule update --init --recursive

build_script:
  - git submodule update --init --recursive
  - python support/appveyor-build.py

on_failure:
  - appveyor PushArtifact Testing/Temporary/LastTest.log
  - appveyor AddTest test

# Uncomment this to debug AppVeyor failures.
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
# update